### ISSUE TITLE
Seek your assistance with the code provided in your article

### ISSUE THREAD

**Issue by CHI-marine** [jpmichael93/Publications#1]
I encountered some issues when trying to replicate the code you provided. In the command colnames(DAstimactive09_fortreemap)[34:35]<-c('maxcoef_09','Genus_overlap_09'), I couldn't find information on how Genus_overlap_09 is calculated. Additionally, it seems that the computation part for DAstimactive17_fortreemap has been omitted. I attempted to create DAstimactive17_fortreemap following the methodology used for DAstimactive09_fortreemap, with 539 rows and 40 columns. As a result, I am puzzled by the extra 4 columns when assigning names in colnames(DAstimactive17_fortreemap)[43:44]<-c('maxcoef_17','Genus_overlap_17'). Could this be due to an issue with the DAstimactive17 object in the preceding steps? Once again, thank you for generously sharing the code, and I look forward to your reply.

**Comment by jpmichael93** [comment]
Hi, thanks for checking the code out! I apologize for the issues you are having, the uploaded file was combined from a few disparate code files and it looks like I missed some snippets. The Genus_overlap columns are simply genus, but with a * if the ASV is overlapping (generated for a different figure).  The DAstimactive17_fortreemap object is generated in the same way as the DAstimactive09_fortreemap, but using different columns representing the different timepoints (days 4, 17, 31, and 80  for 09 and Days 8, 15, 22, and 50 for 17). The difference in the number of columns is due to the number of timepoints from each year of sampling. In retrospect, the code should reference column names (which I have corrected in the supplemental file). 
Anyways, 'WR_EVO_suppcode.txt' should generate the objects you need. It references the lines in the original code file.


[WR_EVO_suppcode.txt](https://github.com/jpmichael93/Publications/files/14911084/WR_EVO_suppcode.txt)

**Comment by CHI-marine** [comment]
Thank you for your careful reply. Following the additional code and instructions you provided, I have successfully run the code. Once again, I appreciate your generous help, thank you.
